name: aeg-core
region: nyc
services:
  - name: core-api
    github:
      repo: CarlosLDC/aeg-core
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 8080
    health_check:
      http_path: /actuator/health
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    envs:
      - key: SPRING_DATASOURCE_URL
        value: ${DB_URL}
      - key: SPRING_DATASOURCE_USERNAME
        value: ${DB_USERNAME}
      - key: SPRING_DATASOURCE_PASSWORD
        value: ${DB_PASSWORD}
