name: aeg-core
region: nyc
services:
  - name: core-api
    github:
      repo: CarlosLDC/aeg-core
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 8080
    health_check:
      http_path: /actuator/health
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    envs:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://private-db-postgresql-nyc1-16442-do-user-35225255-0.l.db.ondigitalocean.com:25060/defaultdb?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: doadmin
      - key: SPRING_DATASOURCE_PASSWORD
        value: SET_IN_APP_PLATFORM
      - key: MQTT_URL
        value: tcp://10.116.0.4:1883
      - key: SPRING_FLYWAY_ENABLED
        value: "false"
