-- Prerrequisitos para la FK de contratos_centros_servicio (idénticos a las entidades JPA del proyecto).
create table if not exists public.empresas (
  id bigint generated by default as identity not null,
  razon_social varchar(255),
  created_at timestamp not null,
  rif varchar(255) not null,
  tipo_contribuyente varchar(255) not null,
  constraint empresas_pkey primary key (id),
  constraint uk_empresas_rif unique (rif)
);

create table if not exists public.sucursales (
  id bigint generated by default as identity not null,
  id_empresa bigint not null,
  ciudad varchar(255) not null,
  estado varchar(255) not null,
  direccion varchar(255),
  telefono varchar(255),
  correo varchar(255),
  created_at timestamp with time zone not null,
  es_cliente boolean default false,
  es_distribuidora boolean default false,
  es_centro_servicio boolean default false,
  constraint sucursales_pkey primary key (id),
  constraint sucursales_id_empresa_fkey foreign key (id_empresa) references public.empresas (id)
);

create table if not exists public.centros_servicio (
  id bigint generated by default as identity not null,
  id_sucursal bigint not null,
  created_at timestamp not null,
  constraint centros_servicio_pkey primary key (id),
  constraint centros_servicio_id_sucursal_fkey foreign key (id_sucursal) references public.sucursales (id)
);

create table if not exists public.contratos_centros_servicio (
  id bigint generated by default as identity not null,
  fecha_inicio date not null,
  fecha_fin date not null,
  created_at timestamp with time zone not null default now(),
  id_centro_servicio bigint not null,
  url_fotos text[] not null,
  constraint contratos_pkey primary key (id),
  constraint contratos_centros_servicio_id_centro_servicio_fkey foreign key (id_centro_servicio) references public.centros_servicio (id)
);
