-- distribuidoras por si el esquema aún no la tiene (FK de contratos_distribuidoras)
create table if not exists public.distribuidoras (
  id bigint generated by default as identity not null,
  id_sucursal bigint not null,
  created_at timestamp not null,
  constraint distribuidoras_pkey primary key (id),
  constraint distribuidoras_id_sucursal_fkey foreign key (id_sucursal) references public.sucursales (id)
);

create table if not exists public.contratos_distribuidoras (
  id bigint generated by default as identity not null,
  fecha_inicio date not null,
  fecha_fin date not null,
  created_at timestamp with time zone not null default now(),
  id_distribuidora bigint not null,
  url_fotos text[] not null,
  constraint contratos_distribuidoras_pkey primary key (id),
  constraint contratos_distribuidoras_id_distribuidora_fkey foreign key (id_distribuidora) references public.distribuidoras (id)
);
