create table if not exists public.firmwares (
  id bigint generated by default as identity not null,
  version text not null,
  nombre_archivo text not null,
  tamano_bytes bigint not null,
  checksum_sha256 text not null,
  id_modelo_impresora bigint,
  notas text,
  created_at timestamp with time zone not null,
  constraint firmwares_pkey primary key (id),
  constraint firmwares_nombre_archivo_key unique (nombre_archivo),
  constraint firmwares_id_modelo_impresora_fkey
    foreign key (id_modelo_impresora) references public.modelos_impresora (id)
);

create unique index if not exists firmwares_version_model_uq
  on public.firmwares (version, id_modelo_impresora)
  where id_modelo_impresora is not null;

create unique index if not exists firmwares_version_generic_uq
  on public.firmwares (version)
  where id_modelo_impresora is null;
