do $$ begin
    create type public.tipo_empleado as enum (
        'administrativo',
        'tecnico',
        'vendedor',
        'gerente'
    );
exception
    when duplicate_object then null;
end $$;

create table if not exists public.empleados (
  id bigint generated by default as identity not null,
  cedula text not null,
  nombre text not null,
  telefono text not null,
  correo text not null,
  created_at timestamp with time zone not null default now(),
  tipo public.tipo_empleado not null,
  id_sucursal bigint not null,
  constraint empleados_pkey primary key (id),
  constraint empleados_cedula_key unique (cedula),
  constraint empleados_id_sucursal_fkey foreign key (id_sucursal) references public.sucursales (id)
);
