create table if not exists public.distribuidores (
  id bigint generated by default as identity not null,
  id_empleado bigint not null,
  created_at timestamp with time zone not null default now(),
  constraint distribuidores_pkey primary key (id),
  constraint distribuidores_id_empleado_fkey foreign key (id_empleado) references public.empleados (id)
);
