create table if not exists public.tecnicos (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  id_empleado bigint not null,
  constraint tecnicos_pkey primary key (id),
  constraint tecnicos_id_empleado_fkey foreign key (id_empleado) references public.empleados (id)
);
