create table if not exists public.inspecciones_anuales (
  id bigint generated by default as identity not null,
  id_impresora bigint not null,
  id_empleado bigint not null,
  precinto_violentado boolean not null,
  observaciones text null,
  created_at timestamp with time zone not null default now(),
  url_fotos text[] not null,
  fecha date not null default current_date,
  constraint inspecciones_anuales_pkey primary key (id),
  constraint inspecciones_anuales_id_empleado_fkey foreign key (id_empleado) references public.empleados (id),
  constraint inspecciones_anuales_id_impresora_fkey foreign key (id_impresora) references public.impresoras (id)
);
