-- precintos (entidad Seal); requerido por FKs de servicios_tecnicos
create table if not exists public.precintos (
  id bigint generated by default as identity not null,
  id_impresora bigint,
  serial text not null,
  created_at timestamp with time zone not null,
  fecha_instalacion timestamp with time zone,
  fecha_retiro timestamp with time zone,
  color text not null,
  estatus text not null,
  constraint precintos_pkey primary key (id),
  constraint precintos_id_impresora_fkey foreign key (id_impresora) references public.impresoras (id)
);

create table if not exists public.servicios_tecnicos (
  id bigint generated by default as identity not null,
  id_impresora bigint not null,
  id_tecnico bigint not null,
  id_centro_servicio bigint,
  precinto_violentado boolean not null,
  observaciones text,
  fecha_inicio timestamp with time zone not null,
  created_at timestamp with time zone not null default now(),
  fecha_fin timestamp with time zone not null,
  url_fotos text[] not null,
  id_precinto_instalado bigint,
  id_precinto_retirado bigint,
  reporte_z_inicial integer not null,
  reporte_z_final integer not null,
  costo numeric not null,
  falla_reportada text not null,
  fecha_solicitud date not null,
  fecha_z_inicial timestamp with time zone not null,
  fecha_z_final timestamp with time zone not null,
  id_distribuidora bigint,
  constraint servicios_tecnicos_pkey primary key (id),
  constraint servicios_tecnicos_id_distribuidora_fkey foreign key (id_distribuidora) references public.distribuidoras (id),
  constraint servicios_tecnicos_id_impresora_fkey foreign key (id_impresora) references public.impresoras (id),
  constraint servicios_tecnicos_id_centro_servicio_fkey foreign key (id_centro_servicio) references public.centros_servicio (id),
  constraint servicios_tecnicos_id_precinto_retirado_fkey foreign key (id_precinto_retirado) references public.precintos (id),
  constraint servicios_tecnicos_id_tecnico_fkey foreign key (id_tecnico) references public.tecnicos (id),
  constraint servicios_tecnicos_id_precinto_instalado_fkey foreign key (id_precinto_instalado) references public.precintos (id)
);
