-- Migración retroactiva idempotente: crea tablas que el modelo JPA usa y que no
-- estaban cubiertas por migraciones anteriores. Solo CREATE IF NOT EXISTS: no
-- DROP, TRUNCATE ni DELETE; no modifica filas existentes.

create table if not exists public.software (
  id bigint generated by default as identity not null,
  nombre text not null,
  version text not null,
  created_at timestamp with time zone not null,
  constraint software_pkey primary key (id)
);

create table if not exists public.modelos_impresora (
  id bigint generated by default as identity not null,
  marca text not null,
  codigo_modelo text not null,
  providencia text,
  fecha_homologacion date,
  created_at timestamp with time zone not null,
  precio numeric not null,
  constraint modelos_impresora_pkey primary key (id)
);

create table if not exists public.clientes (
  id bigint generated by default as identity not null,
  id_sucursal bigint not null,
  created_at timestamp not null,
  constraint clientes_pkey primary key (id),
  constraint clientes_id_sucursal_fkey foreign key (id_sucursal) references public.sucursales (id)
);

create table if not exists public.software_lenguajes_programacion (
  software_id bigint not null,
  lenguaje varchar(255) not null,
  constraint software_lenguajes_programacion_pkey primary key (software_id, lenguaje),
  constraint software_lenguajes_programacion_software_id_fkey foreign key (software_id) references public.software (id) on delete cascade
);

create table if not exists public.software_sistemas_operativos (
  software_id bigint not null,
  sistema varchar(255) not null,
  constraint software_sistemas_operativos_pkey primary key (software_id, sistema),
  constraint software_sistemas_operativos_software_id_fkey foreign key (software_id) references public.software (id) on delete cascade
);

create table if not exists public.impresoras (
  id bigint generated by default as identity not null,
  id_modelo_impresora bigint,
  id_software bigint,
  id_cliente bigint,
  serial_fiscal text not null,
  precio_venta_final numeric,
  created_at timestamp with time zone not null,
  estatus text not null,
  id_distribuidora bigint,
  se_pago boolean not null default false,
  fecha_instalacion timestamp with time zone,
  version_firmware text,
  direccion_mac text,
  tipo_dispositivo text not null,
  constraint impresoras_pkey primary key (id),
  constraint impresoras_serial_fiscal_key unique (serial_fiscal),
  constraint impresoras_id_modelo_impresora_fkey foreign key (id_modelo_impresora) references public.modelos_impresora (id),
  constraint impresoras_id_software_fkey foreign key (id_software) references public.software (id),
  constraint impresoras_id_cliente_fkey foreign key (id_cliente) references public.clientes (id),
  constraint impresoras_id_distribuidora_fkey foreign key (id_distribuidora) references public.distribuidoras (id)
);
